### ISSUE TITLE
Compilation error: hosted_payment_controller

### ISSUE THREAD

**Issue by alaadahmed** [aviacommerce/avia#352]
After following Frontend/Backend installation and configuration process.
I got compilation error:
```
== Compilation error in file lib/snitch_api_web/controllers/hosted_payment_controller.ex ==
** (CompileError) lib/snitch_api_web/controllers/hosted_payment_controller.ex:174: invalid literal nil in <<>>
    (elixir) src/elixir_bitstring.erl:27: :elixir_bitstring.expand/7
    (elixir) src/elixir_bitstring.erl:20: :elixir_bitstring.expand/4
    (elixir) expanding macro: Kernel.<>/2
    lib/snitch_api_web/controllers/hosted_payment_controller.ex:174: SnitchApiWeb.HostedPaymentController.payubiz_params_setup/1
    (elixir) lib/kernel/parallel_compiler.ex:206: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```
Did I miss anything?

**Comment by alaadahmed** [comment]
OK my fault, I check now on your website and you mention such issue and the solution for it. I will check that.
